In [67]:
%pip install numpy Pillow

Note: you may need to restart the kernel to use updated packages.


In [68]:
import numpy as np
from PIL import Image

In [ ]:
def gaussian_filtering(image, image_width, image_height):
    # fixed Gaussian kernel
    gaussian_kernel = np.array([[1, 2, 1], [2, 4, 2], [1, 2, 1]]) / 16
    kernel_size = gaussian_kernel.shape[0]

    extended_image = np.pad(image, pad_width=1, mode="edge")

    # debug: print the extended image
    print("Extended image:")
    print(extended_image)

    filtered_image = np.zeros_like(image, dtype=np.float64)
    for i in range(image_height):
        for j in range(image_width):
            region = extended_image[i : i + kernel_size, j : j + kernel_size]
            filtered_image[i, j] = np.sum(region * gaussian_kernel)
    return filtered_image

In [70]:
left_image = np.array(Image.open("assets/original_left_image.png").convert('L'))

print("Original left image:")
print(left_image)
gaussian_left_image = gaussian_filtering(left_image, len(left_image[0]), len(left_image))

Original left image:
[[ 40  37  34 ...  21  21  21]
 [ 30  30  28 ...  22  21  21]
 [ 20  20  24 ...  23  21  22]
 ...
 [ 94 103 106 ...  76  68  59]
 [ 93  99 100 ...  60  41  43]
 [ 85  88  89 ...  38  43  41]]
Extended image:
[[40 40 37 ... 21 21 21]
 [40 40 37 ... 21 21 21]
 [30 30 30 ... 21 21 21]
 ...
 [93 93 99 ... 41 43 43]
 [85 85 88 ... 43 41 41]
 [85 85 88 ... 43 41 41]]


In [71]:
right_image = np.array(Image.open("assets/original_right_image.png").convert('L'))
print("Original right image:")
print(right_image)
gaussian_right_image = gaussian_filtering(right_image, len(right_image[0]), len(right_image))

Original right image:
[[169 164 159 ... 152 147 139]
 [164 161 157 ... 146 139 131]
 [162 161 161 ... 139 135 130]
 ...
 [ 64  50  56 ...  58  83  82]
 [ 65  71  69 ...  52  63  63]
 [ 71  70  74 ...  38  45  47]]
Extended image:
[[169 169 164 ... 147 139 139]
 [169 169 164 ... 147 139 139]
 [164 164 161 ... 139 131 131]
 ...
 [ 65  65  71 ...  63  63  63]
 [ 71  71  70 ...  45  47  47]
 [ 71  71  70 ...  45  47  47]]


In [73]:
sample_gaussian_left_image = np.array(Image.open("assets/gaussian_filter_left_image.png").convert('L'))
sample_gaussian_right_image = np.array(Image.open("assets/gaussian_filter_right_image.png").convert('L'))

print("Sample Gaussian filtered left image:")
print(sample_gaussian_left_image)
print("Gaussian filtered left image:")

rounded_gaussian_left_image = np.round(gaussian_left_image)
rounded_gaussian_right_image = np.round(gaussian_right_image)

print(rounded_gaussian_left_image)
print(rounded_gaussian_right_image)

print(np.array_equal(sample_gaussian_left_image, rounded_gaussian_left_image))
print(np.array_equal(sample_gaussian_right_image, rounded_gaussian_right_image))

Sample Gaussian filtered left image:
[[ 37  35  35 ...  22  21  21]
 [ 30  29  29 ...  23  21  21]
 [ 24  23  24 ...  23  22  22]
 ...
 [ 96  99 101 ...  70  64  61]
 [ 93  96  98 ...  57  50  47]
 [ 88  90  91 ...  44  42  42]]
Gaussian filtered left image:
[[ 37.  35.  35. ...  22.  21.  21.]
 [ 30.  29.  29. ...  23.  21.  21.]
 [ 24.  23.  24. ...  23.  22.  22.]
 ...
 [ 96.  99. 101. ...  70.  64.  61.]
 [ 93.  96.  98. ...  57.  50.  47.]
 [ 88.  90.  91. ...  44.  42.  42.]]
[[167. 163. 160. ... 149. 144. 139.]
 [164. 162. 160. ... 144. 140. 135.]
 [162. 162. 162. ... 141. 138. 135.]
 ...
 [ 68.  66.  67. ...  53.  64.  68.]
 [ 66.  66.  68. ...  51.  60.  64.]
 [ 70.  71.  73. ...  42.  48.  51.]]
True
True
