# Simple Gaussian Filtering Demo

Apply Gaussian filter with using extend padding on original image

The filter kernel is:
$$1/16
\begin{bmatrix}
1 & 2 & 1 \\
2 & 4 & 2 \\
1 & 2 & 1
\end{bmatrix}
$$

### Sample Results

| Original Images    | Filtered Gaussian Images |
| -------- | ------- |
| [![Left Image](./assets/original_left_image.png)](./assests/original_left_image.png)  | [![Left Image](./assets/gaussian_filter_left_image.png)](./assests/gaussian_filter_left_image.png)    |
| [![Right Image](./assets/original_right_image.png)](./assests/original_right_image.png) | [![Right Image](./assets/gaussian_filter_right_image.png)](./assests/gaussian_filter_right_image.png)     |


## Dependencies

In [11]:
%pip install numpy Pillow

Note: you may need to restart the kernel to use updated packages.


In [12]:
import numpy as np
from PIL import Image
from src.utils import round_matrix
from src import harris

## Gaussian Filtering function

### Load orignal images and display the matrices

In [13]:
left_image = np.array(Image.open("assets/original_left_image.png").convert('L'))

print("Original left image:")
print(left_image)
gaussian_left_image = harris.gaussian_filtering(left_image, len(left_image[0]), len(left_image))

Original left image:
[[ 40  37  34 ...  21  21  21]
 [ 30  30  28 ...  22  21  21]
 [ 20  20  24 ...  23  21  22]
 ...
 [ 94 103 106 ...  76  68  59]
 [ 93  99 100 ...  60  41  43]
 [ 85  88  89 ...  38  43  41]]


In [14]:
right_image = np.array(Image.open("assets/original_right_image.png").convert('L'))
print("Original right image:")
print(right_image)
gaussian_right_image = harris.gaussian_filtering(right_image, len(right_image[0]), len(right_image))

Original right image:
[[169 164 159 ... 152 147 139]
 [164 161 157 ... 146 139 131]
 [162 161 161 ... 139 135 130]
 ...
 [ 64  50  56 ...  58  83  82]
 [ 65  71  69 ...  52  63  63]
 [ 71  70  74 ...  38  45  47]]


### Verfiy the result by comparing sample filtered images

In [16]:
sample_gaussian_left_image = np.array(Image.open("assets/gaussian_filter_left_image.png").convert('L'))
sample_gaussian_right_image = np.array(Image.open("assets/gaussian_filter_right_image.png").convert('L'))

rounded_gaussian_left_image = np.round(gaussian_left_image)
rounded_gaussian_right_image = np.round(gaussian_right_image)

print("Gaussian filtered left image:")
print(rounded_gaussian_left_image)
print("\nGaussian filtered right image:")
print(rounded_gaussian_right_image)

print("\nVerifying results are identical to sample images:")
print(np.array_equal(sample_gaussian_left_image, rounded_gaussian_left_image))
print(np.array_equal(sample_gaussian_right_image, rounded_gaussian_right_image))

Gaussian filtered left image:
[[ 37.  35.  35. ...  22.  21.  21.]
 [ 30.  29.  29. ...  23.  21.  21.]
 [ 24.  23.  24. ...  23.  22.  22.]
 ...
 [ 96.  99. 101. ...  70.  64.  61.]
 [ 93.  96.  98. ...  57.  50.  47.]
 [ 88.  90.  91. ...  44.  42.  42.]]

Gaussian filtered right image:
[[167. 163. 160. ... 149. 144. 139.]
 [164. 162. 160. ... 144. 140. 135.]
 [162. 162. 162. ... 141. 138. 135.]
 ...
 [ 68.  66.  67. ...  53.  64.  68.]
 [ 66.  66.  68. ...  51.  60.  64.]
 [ 70.  71.  73. ...  42.  48.  51.]]

Verifying results are identical to sample images:
True
True
