# Simple Gaussian Filtering Demo

Apply Gaussian filter with using extend padding on original image

The filter kernel is:
$$1/16
\begin{bmatrix}
1 & 2 & 1 \\
2 & 4 & 2 \\
1 & 2 & 1
\end{bmatrix}
$$

### Sample Results

| Original Images    | Filtered Gaussian Images |
| -------- | ------- |
| [![Left Image](./assets/original_left_image.png)](./assests/original_left_image.png)  | [![Left Image](./assets/gaussian_filter_left_image.png)](./assests/gaussian_filter_left_image.png)    |
| [![Right Image](./assets/original_right_image.png)](./assests/original_right_image.png) | [![Right Image](./assets/gaussian_filter_right_image.png)](./assests/gaussian_filter_right_image.png)     |


## Dependencies

In [74]:
%pip install numpy Pillow

Note: you may need to restart the kernel to use updated packages.


In [89]:
import numpy as np
from PIL import Image
from src.utils import round_matrix

## Gaussian Filtering function

In [76]:
def gaussian_filtering(image, image_width, image_height):
    # fixed Gaussian kernel
    gaussian_kernel = np.array([[1, 2, 1], [2, 4, 2], [1, 2, 1]]) / 16
    kernel_size = gaussian_kernel.shape[0]

    extended_image = np.pad(image, pad_width=1, mode="edge")

    # debug: print the extended image
    print("Extended image:")
    print(extended_image)

    filtered_image = np.zeros_like(image, dtype=np.float64)
    for i in range(image_height):
        for j in range(image_width):
            region = extended_image[i : i + kernel_size, j : j + kernel_size]
            filtered_image[i, j] = np.sum(region * gaussian_kernel)
    return filtered_image

#### Testing

Given matrix

$$ I = 
\begin{bmatrix}
49 & 223 & 46 & 174 & 128 \\
84 & 165 & 223 & 233 & 97 \\
168 & 87 & 187 & 42 & 62 \\
115 & 128 & 100 & 202 & 3 \\
71 & 89 & 76 & 50 & 244
\end{bmatrix}
$$

Then the extending matrix using repeated at the border (BorderBoundaryPadding). This means that at the four edges of the image, as well as at the four corner locations, the pixel intensities are extended (copied) to the outside of the image.

$$ I_{extended} = 
\begin{bmatrix}
\underline{49} & \underline{49} & \underline{223} & \underline{46} & \underline{174} & \underline{128} & \underline{128} \\
\underline{49} & 49 & 223 & 46 & 174 & 128 & \underline{128} \\
\underline{84} & 84 & 165 & 223 & 233 & 97 & \underline{97} \\
\underline{168} & 168 & 87 & 187 & 42 & 62 & \underline{62} \\
\underline{115} & 115 & 128 & 100 & 202 & 3 & \underline{3} \\
\underline{71} & \textbf{71} & 89 & 76 & 50 & 244 & \underline{244} \\
\underline{71} & \underline{71} & \underline{89} & \underline{76} & \underline{50} & \underline{244} & \underline{244} 
\end{bmatrix}
$$

Calculate the value at bottom left, aka **71**

$$
(71*(1+4+2+2) + 115*(1+2) + 128 + 89*(1+ 2)/16=1379/16=86.1875
$$

In [90]:
I = np.array([
    [49 , 223 , 46 , 174 , 128],
    [84 , 165 , 223 , 233 , 97],
    [168 , 87 , 187 , 42 , 62],
    [115 , 128 , 100 , 202 , 3],
    [71 , 89 , 76 , 50 , 244]
])

fitered_I = gaussian_filtering(I, len(I[0]), len(I))

print("Filtered I:")
print(fitered_I)
print("Rounded Filtered I:")
print(round_matrix(fitered_I))

Extended image:
[[ 49  49 223  46 174 128 128]
 [ 49  49 223  46 174 128 128]
 [ 84  84 165 223 233  97  97]
 [168 168  87 187  42  62  62]
 [115 115 128 100 202   3   3]
 [ 71  71  89  76  50 244 244]
 [ 71  71  89  76  50 244 244]]
Filtered I:
[[ 95.4375 141.25   144.4375 147.     137.375 ]
 [112.1875 146.5    167.5    151.6875 114.625 ]
 [129.5    135.375  148.75   122.4375  74.4375]
 [114.9375 112.25   115.875  110.4375  89.5   ]
 [ 86.1875  90.375   87.6875 110.4375 159.8125]]
Rounded Filtered I:
[[ 95 141 144 147 137]
 [112 147 168 152 115]
 [130 135 149 122  74]
 [115 112 116 110  90]
 [ 86  90  88 110 160]]


## Apply to real Images

### Load orignal images and display the matrices

In [77]:
left_image = np.array(Image.open("assets/original_left_image.png").convert('L'))

print("Original left image:")
print(left_image)
gaussian_left_image = gaussian_filtering(left_image, len(left_image[0]), len(left_image))

Original left image:
[[ 40  37  34 ...  21  21  21]
 [ 30  30  28 ...  22  21  21]
 [ 20  20  24 ...  23  21  22]
 ...
 [ 94 103 106 ...  76  68  59]
 [ 93  99 100 ...  60  41  43]
 [ 85  88  89 ...  38  43  41]]
Extended image:
[[40 40 37 ... 21 21 21]
 [40 40 37 ... 21 21 21]
 [30 30 30 ... 21 21 21]
 ...
 [93 93 99 ... 41 43 43]
 [85 85 88 ... 43 41 41]
 [85 85 88 ... 43 41 41]]


In [78]:
right_image = np.array(Image.open("assets/original_right_image.png").convert('L'))
print("Original right image:")
print(right_image)
gaussian_right_image = gaussian_filtering(right_image, len(right_image[0]), len(right_image))

Original right image:
[[169 164 159 ... 152 147 139]
 [164 161 157 ... 146 139 131]
 [162 161 161 ... 139 135 130]
 ...
 [ 64  50  56 ...  58  83  82]
 [ 65  71  69 ...  52  63  63]
 [ 71  70  74 ...  38  45  47]]
Extended image:
[[169 169 164 ... 147 139 139]
 [169 169 164 ... 147 139 139]
 [164 164 161 ... 139 131 131]
 ...
 [ 65  65  71 ...  63  63  63]
 [ 71  71  70 ...  45  47  47]
 [ 71  71  70 ...  45  47  47]]


### Verfiy the result by comparing sample filtered images

In [84]:
sample_gaussian_left_image = np.array(Image.open("assets/gaussian_filter_left_image.png").convert('L'))
sample_gaussian_right_image = np.array(Image.open("assets/gaussian_filter_right_image.png").convert('L'))

rounded_gaussian_left_image = np.round(gaussian_left_image)
rounded_gaussian_right_image = np.round(gaussian_right_image)

print("Sample Gaussian filtered left image:")
print(sample_gaussian_left_image)
print("Gaussian filtered left image:")
print(rounded_gaussian_left_image)

print("Verifying results are identical to sample images:")
print(np.array_equal(sample_gaussian_left_image, rounded_gaussian_left_image))
print(np.array_equal(sample_gaussian_right_image, rounded_gaussian_right_image))

Sample Gaussian filtered left image:
[[ 37  35  35 ...  22  21  21]
 [ 30  29  29 ...  23  21  21]
 [ 24  23  24 ...  23  22  22]
 ...
 [ 96  99 101 ...  70  64  61]
 [ 93  96  98 ...  57  50  47]
 [ 88  90  91 ...  44  42  42]]
Gaussian filtered left image:
[[ 37.  35.  35. ...  22.  21.  21.]
 [ 30.  29.  29. ...  23.  21.  21.]
 [ 24.  23.  24. ...  23.  22.  22.]
 ...
 [ 96.  99. 101. ...  70.  64.  61.]
 [ 93.  96.  98. ...  57.  50.  47.]
 [ 88.  90.  91. ...  44.  42.  42.]]
Verifying results are identical to sample images:
True
True
