In [4]:
import numpy as np

## A. Implement compute_homo

In [5]:
def compute_homo(matched_corner_pairs):
    A = np.zeros((2 * len(matched_corner_pairs), 9))
    
    for i, (pt1, pt2) in enumerate(matched_corner_pairs):
        x1, y1 = pt1
        x2, y2 = pt2
        
        A[2*i] = [0, 0, 0, x1, y1, 1, -y2*x1, -y2*y1, -y2]
        A[2*i + 1] = [x1, y1, 1, 0, 0, 0, -x2*x1, -x2*y1, -x2]
        
    print("Matrix A:")
    print(A)
    
    _U,_D,Vt = np.linalg.svd(A) 
    h = Vt[-1]
    H = h.reshape(3, 3)
    return H

## B. Testing if the implementation is correct

### B.1. The A matrix in 773-2026 Assignment 1 Phase 3 (Theory) - Question 1


In [6]:
# # Theory
# # S1 = {(1, 1, 1), (2, 3, 1), (4, 2, 1), (3, 5, 1))}
# # S2 = {(3, 4, 1), (5, 8, 1), (9, 6, 1), (7, 12, 1)},
theory_pairs = np.array(
    [
        [[2, 3], [6, 1]],
        [[5, 7], [9, 5]],
        [[8, 4], [12, 2]],
        [[6, 9], [10, 7]],
    ]
)
theory_H = compute_homo(theory_pairs)

print(theory_H)

Matrix A:
[[  0.   0.   0.   2.   3.   1.  -2.  -3.  -1.]
 [  2.   3.   1.   0.   0.   0. -12. -18.  -6.]
 [  0.   0.   0.   5.   7.   1. -25. -35.  -5.]
 [  5.   7.   1.   0.   0.   0. -45. -63.  -9.]
 [  0.   0.   0.   8.   4.   1. -16.  -8.  -2.]
 [  8.   4.   1.   0.   0.   0. -96. -48. -12.]
 [  0.   0.   0.   6.   9.   1. -42. -63.  -7.]
 [  6.   9.   1.   0.   0.   0. -60. -90. -10.]]
[[ 2.08514414e-01  3.56995755e-15  8.34057656e-01]
 [-1.40648228e-15  2.08514414e-01 -4.17028828e-01]
 [-5.64163588e-16  2.75552517e-16  2.08514414e-01]]


### B.2. The H matrix in Tutorial

In [8]:
def find_intersection_of_two_3D_lines(p1, p2, p3, p4):
    # Direction vectors for both lines
    v1 = p2 - p1
    v2 = p4 - p3
    
    # Vector connecting the starting points
    c = p3 - p1
    
    # Cross product of the direction vectors
    v1_cross_v2 = np.cross(v1, v2)
    
    # Squared magnitude of the cross product
    norm_sq = np.dot(v1_cross_v2, v1_cross_v2)
    
    # Guard against parallel or collinear lines (where cross product is zero vector)
    if np.isclose(norm_sq, 0):
        raise ValueError("Lines are parallel or collinear; no unique intersection point.")
    
    # Calculate the scalar t1 for the first line
    c_cross_v2 = np.cross(c, v2)
    t1 = np.dot(c_cross_v2, v1_cross_v2) / norm_sq
    
    # Substitute t1 back into the first line equation to find the exact intersection
    exact_intersection = p1 + t1 * v1
    
    # Round to the nearest integer and return
    return np.round(exact_intersection)

p1 = np.array([5, 1, 10])
p2 = np.array([6, 1, 7])
p3 = np.array([8, -4, 8])
p4 = np.array([3, -1, 9])

X, Y, Z = find_intersection_of_two_3D_lines(p1, p2, p3, p4)
print(f"The intersection point of two 3D lines: X = {X}, Y = {Y}, Z = {Z}")

The intersection point of two 3D lines: X = 5.0, Y = 1.0, Z = 9.0
