# Optimal Homography Transformation

In [ ]:
import numpy as np

In [17]:
P_1_old = np.array([
    [2450, -4550, 100],
    [212.5, -487.5, -5112.5],
    [-0.7, -0.7, -0.1]])
P_1_new = np.array([
    [425, -1260, 5055],
    [2768.75, -4182.5, -958.75],
    [-0.65, -0.74, 0.17]])

P_2_old = np.array([
    [2450, -4550, -100],
    [712.5, -337.5, -5225],
    [-0.7, -0.7, -0.2]])
P_2_new = np.array([
    [425, -1260, 5055],
    [2768.75, -4182.5, -958.75],
    [-0.65, -0.74, 0.17]])

In [21]:
np.round(np.linalg.inv(P_1_old), 2)

array([[ 0.  ,  0.  , -0.93],
       [-0.  ,  0.  , -0.5 ],
       [ 0.  , -0.  ,  0.01]])

In [24]:
np.round(P_1_new @ np.linalg.inv(P_1_old), 2)


array([[ 3.4000e-01, -9.9000e-01,  2.8121e+02],
       [ 9.7000e-01,  2.2000e-01, -4.8977e+02],
       [ 0.0000e+00, -0.0000e+00,  9.8000e-01]])

In [25]:
np.round(P_2_new @ np.linalg.inv(P_2_old), 2)

array([[ 3.9000e-01, -9.7000e-01, -2.4056e+02],
       [ 9.7000e-01,  1.8000e-01, -3.9103e+02],
       [ 0.0000e+00, -0.0000e+00,  9.4000e-01]])