# Optimal Homography Transformation

In [41]:
import numpy as np

# Transformation

## Question 1
You are given two sets of 2D points, `A` and `B`, representing corresponding feature coordinates in two images. Write a Python function called `procrustes_align(A, B)` that:

- Centers both sets of points.
- Computes the best-fitting rotation matrix using SVD of the cross-covariance matrix.
- Applies the rotation to align `A` to `B`.

Note 1: Assume the numpy Python package has been imported before the execution of the function `procrustes_align(A, B)`. Please see the example below!

Note 2: Your implemented function should return the aligned points and the rotation matrix.

Note 3: Do not round any result in your implementation.

In [42]:
def procrustes_align(A, B):
    A = np.asarray(A)
    B = np.asarray(B)
    
    centroid_A = np.mean(A, axis=0)
    centroid_B = np.mean(B, axis=0)
    
    A_centered = A - centroid_A
    B_centered = B - centroid_B
    
    H = A_centered.T @ B_centered
    
    U, S, Vt = np.linalg.svd(H)
    
    d = np.linalg.det(U @ Vt)
    D = np.diag([1, d])
    R = U @ D @ Vt
    
    A_centered_aligned = A_centered @ R.T
    
    A_aligned = A_centered_aligned + centroid_B
    
    return A_aligned, R

### Test 1

```(python)
Aligned A:
 [[2. 2.]
 [3. 2.]
 [2. 3.]]
Rotation Matrix:
 [[ 1.00000000e+00  8.90187929e-18]
 [-2.91647349e-16  1.00000000e+00]]
```

In [43]:
A = np.array([[1.0, 1.0], [2.0, 1.0], [1.0, 2.0]])
B = np.array([[2.0, 2.0], [3.0, 2.0], [2.0, 3.0]])
aligned_A, rotation_matrix = procrustes_align(A, B)
print("Aligned A:\n", aligned_A)
print("Rotation Matrix:\n", rotation_matrix)

Aligned A:
 [[2. 2.]
 [3. 2.]
 [2. 3.]]
Rotation Matrix:
 [[ 1.00000000e+00  7.78822944e-17]
 [-1.67155782e-16  1.00000000e+00]]


### Test 2

```(python)
Aligned A:
 [[ 9. 18.]
 [ 7. 16.]
 [ 5. 14.]]
Rotation Matrix:
 [[-1.00000000e+00  5.48888227e-17]
 [-2.45660405e-16 -1.00000000e+00]]
```

In [44]:
A = numpy.array([[ 1.0,  2.0], [ 3.0,  4.0], [ 5.0,  6.0]])
B = numpy.array([[ 9.0, 18.0], [ 7.0, 16.0], [ 5.0, 14.0]])
aligned_A, rotation_matrix = procrustes_align(A, B)
print("Aligned A:\n", aligned_A)
print("Rotation Matrix:\n", rotation_matrix)

Aligned A:
 [[ 9. 18.]
 [ 7. 16.]
 [ 5. 14.]]
Rotation Matrix:
 [[-1.00000000e+00  1.33393446e-16]
 [-8.86511593e-17 -1.00000000e+00]]
