In [33]:
import numpy as np
import math

## Q1: Compute eigenvalues

$$
\lambda_{1,2}=\frac{trace(A)\pm\sqrt{trace(A)^2-4*det(A)}}{2}
$$

In [34]:
def compute_eigenvalues(A):
    trace = A[0][0] + A[1][1]
    determinant = A[0][0] * A[1][1] - A[0][1] * A[1][0]
    discriminant = trace**2 - 4 * determinant

    lambda1 = (trace + math.sqrt(discriminant)) / 2
    lambda2 = (trace - math.sqrt(discriminant)) / 2

    return sorted([lambda1, lambda2], reverse=True)

In [35]:
A = [[4, 2],
     [1, 3]]

lambda_values = compute_eigenvalues(A)
lambda_values = sorted(lambda_values, reverse=True)
print(f"lambda 1: {round(lambda_values[0])}, lambda 2: {round(lambda_values[1])}")

lambda 1: 5, lambda 2: 2


## Sum of Squared Differences (SSD)

In [36]:
def compute_SSD(template, window):
    ssd = 0
    for i in range(len(template)):
        for j in range(len(template[0])):
            ssd += (template[i][j] - window[i][j]) ** 2
    return ssd

In [37]:
template = [[9,  11, 65],
            [11, 71, 12],
            [56, 76, 90]]
window = [[58, 13, 40],
          [52, 77, 64],
          [13, 56, 90]]

result = compute_SSD(template, window)
print("SSD =", result)

SSD = 9700


## Rigid Transformation 

In [38]:
def fitting_a_rigid_transformation(A, B):
    def round_matrix(arr: np.ndarray) -> np.ndarray:
        return np.where(arr >= 0, np.floor(arr + 0.5), np.ceil(arr - 0.5)).astype(np.int64)
    
    A=np.array(A)
    B=np.array(B)

    centeroid_A = np.mean(A, axis=0)
    centeroid_B = np.mean(B, axis=0)
    
    A_centered = A - centeroid_A
    B_centered = B - centeroid_B
    
    print("A_centered.T:\n", A_centered.T)
    print("B_centered:\n", B_centered)
    
    H = A_centered.T @ B_centered
    print("H:\n", H)

    U, _L, Vh = np.linalg.svd(H)
    
    detUVh = np.linalg.det(U @ Vh)
    D = np.diag([1, detUVh])
    
    print("U:\n", U)
    print("D:\n", D)
    print("Vh:\n", Vh)
    
    R = round_matrix(U @ D @ Vh)
    
    t = round_matrix(centeroid_B - R @ centeroid_A)
    
    return R, t

In [39]:
A = [[-3, -10], [-8, -6], [3, -7]]
B = [[3, -9], [-4, 9], [8, -2]]

# A = [[-8, 8], [1, -9], [-3, -1]]
# B = [[4, 10], [-7, 5], [5, -4]]

rotation_matrix, translation_vector = fitting_a_rigid_transformation(A, B)
print("Rotation Matrix:")
print(rotation_matrix)
print("\nTranslation Vector:")
print(translation_vector)

A_centered.T:
 [[-0.33333333 -5.33333333  5.66666667]
 [-2.33333333  1.66666667  0.66666667]]
B_centered:
 [[ 0.66666667 -8.33333333]
 [-6.33333333  9.66666667]
 [ 5.66666667 -1.33333333]]
H:
 [[ 65.66666667 -56.33333333]
 [ -8.33333333  34.66666667]]
U:
 [[-0.94316147  0.33233485]
 [ 0.33233485  0.94316147]]
D:
 [[1. 0.]
 [0. 1.]]
Vh:
 [[-0.70738746  0.70682599]
 [ 0.70682599  0.70738746]]
Rotation Matrix:
[[1 0]
 [0 1]]

Translation Vector:
[5 7]
